name: pokedex
description: Project of test, build a application using the PokeApi and show a list of pokemons and show some details.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.6
  infinite_scroll_pagination: ^3.2.0
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.6
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/